<?php
# This file was automatically generated by the MediaWiki 1.45.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

$hostip = getenv('HOST_IP');

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "murmurpedia";
$wgMetaNamespace = "Murmurpedia";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScript = "/index.php";
$wgScriptPath = "";
## Makale yolu (Tarayıcıda görünen yer)
$wgArticlePath = "/wiki/$1";
// $wgUsePathInfo = true;

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://" . getenv('HOST_IP') . ":8080";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/images/logo_murmur.png",
	'icon' => "$wgResourceBasePath/images/logo_murmur.png",
];
$wgFavicon = $wgScriptPath . "/images/favicon_murmur.ico";
// $wgFavicon = $wgScriptPath . "/images/logo_murmur.svg";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "murmurbot@wiki.murmur.land";
$wgPasswordSender = "murmurbot@wiki.murmur.land";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = getenv('MYSQL_SERVER');
$wgDBname = getenv('MYSQL_DATABASE');
$wgDBuser = getenv('MYSQL_USER');
$wgDBpassword = getenv('MYSQL_PASSWORD');

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";
// No need to set $wgGlobalPreferencesDB if it's the same as $wgSharedDB.
// $wgGlobalPreferencesDB = 'murmurpedia';

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

// $wgSecretKey = "68cda1575db0d2269d06dda49bc29bff765b62249d4aa724cee4ebdcbf322efa";
$wgSecretKey = getenv('MEDIAWIKI_SECRET_KEY');
# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
// $wgUpgradeKey = "de7529196dc9f081";
$wgUpgradeKey = "4a543cc4d048021a";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-sa/4.0/";
$wgRightsText = "Creative Commons Attribution-ShareAlike";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";


# Giriş yapmış kullanıcılar → edit yok
// $wgGroupPermissions['user']['edit'] = false;
// $wgGroupPermissions['user']['createpage'] = false;


# Enabled skins.
# The following skins were automatically enabled:
$wgDefaultSkin = "vector-2022";
$wgVectorResponsive = true;
$wgDefaultMobileSkin = 'minerva';

wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

// Safe loader helpers to avoid fatal errors when optional packages are not present.
$loadSkinIfPresent = static function ( string $name ) use ( $IP ) : void {
	$path = "$IP/skins/$name/skin.json";
	if ( file_exists( $path ) ) {
		wfLoadSkin( $name );
	}
};

$loadExtensionIfPresent = static function ( string $name ) use ( $IP ) : void {
	$path = "$IP/extensions/$name/extension.json";
	if ( file_exists( $path ) ) {
		wfLoadExtension( $name );
	}
};

# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
$loadExtensionIfPresent( 'CodeEditor' );
$loadExtensionIfPresent( 'VisualEditor' );
$loadExtensionIfPresent( 'WikiEditor' );
$loadExtensionIfPresent( 'MobileFrontend' );
$loadExtensionIfPresent( 'GlobalPreferences' );

// wfLoadExtension( 'VisualEditor' ); 

# End of automatically generated settings.
# Add more configuration options below.
$wgShowExceptionDetails = true;
# VisualEditor Ayarları
// $wgDefaultUserOptions['visualeditor-enable'] = 1;
$wgDefaultUserOptions['visualeditor-editor'] = 'visualeditor';
$wgVirtualRestConfig['modules']['parsoid'] = [
    'url' => $wgServer . $wgScriptPath . '/rest.php',
];
$wgVisualEditorNamespaces = [ NS_MAIN, NS_USER, NS_PROJECT ];
$wgResourceLoaderValidateStaticJS = false;


wfLoadExtension('PluggableAuth');
wfLoadExtension('Auth42');
// wfLoadExtension('FlaggedRevs');
wfLoadExtension('ApprovedRevs');

$wgPluggableAuth_Config = [
    "42 ile Giriş" => [
        "plugin" => "Auth42",
        "data" => [
            "ClientID"     => "u-s4t2ud-3439ca88deb81572dd171c078282b6d0555606c252c69dd97b85d7970e27f6ed",
            "ClientSecret" => getenv('AUTH42_CLIENT_SECRET'),
            "RedirectURI"  => "http://" . getenv('HOST_IP') . ":8080/wiki/Special:PluggableAuthLogin"
        ]
    ]
];
$wgDebugLogFile = "/tmp/wiki-debug.log";
$wgPluggableAuth_EnableLocalLogin = true;


# Auth42: Kullanıcı sayfalarında 42 Intra avatarlarının gösterilmesi için
// $wgAllowImageTag = true;
// $wgAllowExternalImagesFrom = [ 'https://cdn.intra.42.fr/' ];

wfLoadExtension('ConfirmAccount');
$wgSessionCacheType = CACHE_DB; // Avoids stale session state across requests.
# Normal kayıt kapalı
$wgGroupPermissions['*']['createaccount'] = false;

# PluggableAuth (42 OAuth) ile otomatik hesap oluşturmaya izin ver
$wgGroupPermissions['*']['autocreateaccount'] = true;
# ConfirmAccount'un auto-create'i engellemesini önle
$wgConfirmAccountAutoCreate = true;
$wgAutoCreateTempUser['enabled'] = false;

# Sadece adminler onaylayabilir
$wgGroupPermissions['sysop']['createaccount'] = true;
 $wgConfirmAccountRequestFormItems = [
 	'UserName'        => [ 'enabled' => true ],
 	'RealName'        => [ 'enabled' => false ],
 	'Biography'       => [ 'enabled' => false, 'minWords' => 50 ],
 	'AreasOfInterest' => [ 'enabled' => false ],
 	'CV'              => [ 'enabled' => false ],
 	'Notes'           => [ 'enabled' => true ],
 	'Links'           => [ 'enabled' => false ],
 	'TermsOfService'  => [ 'enabled' => true ],
 ];

require_once "$IP/custom_settings/Namespaces.php";
require_once "$IP/custom_settings/Permissions.php";
// require_once "$IP/custom_settings/ExtensionSettings.php";
