name: ${COMPOSE_PROJECT_NAME}
services:
  mediawiki:
    build: ./mediawiki
    ports:
      - 0.0.0.0:4431:80
    restart: always
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    volumes:
      # - /var/www/test:/var/www/html
      # - /var/www/wiki.murmur.land/:/var/www/html
      - images:/var/www/html/images
      - vendor:/var/www/html/vendor
      - extensions:/var/www/html/extensions
      - composer_cache:/root/.composer/cache
      - ./mediawiki/conf/:/var/www/html/configs/
      - ./mediawiki/conf/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./mediawiki/conf/composer.json:/var/www/html/composer.local.json
      - ./mediawiki/conf/custom:/var/www/html/custom_settings
      - ./mediawiki/Auth42:/var/www/html/extensions/Auth42
      - ./mediawiki/scripts:/tmp/scripts
      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php
      # This kath /home/g0aeonchannel0/wiki.murmur.land/stack/testimage either does not exist, is not accessible, or is not a valid URL.ey also defines the name of the database host used during setup instead of the default "localhost"
    # network_mode: host
    # networks:
    #   - wiki-db
    env_file:
      - ../.env
  database:
    # networks:
    #   - wiki-db
    # network_mode: host
    build: ./database
    restart: always
    # environment:
    #   # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
    env_file:
      - ../.env
    volumes:
      - db:/var/lib/mysql

# networks:
#   wiki-db:
#     driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_DIR}/${COMPOSE_PROJECT_NAME}_db
  images:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_DIR}/${COMPOSE_PROJECT_NAME}_images
  vendor:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_DIR}/${COMPOSE_PROJECT_NAME}_vendor
  extensions:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_DIR}/${COMPOSE_PROJECT_NAME}_extensions
  composer_cache:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_DIR}/${COMPOSE_PROJECT_NAME}_composer_cache
